In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from matplotlib import font_manager, rc
# 한글 폰트 설정
font_path = "C:/Windows/Fonts/malgun.ttf"  # 사용하고 있는 OS에 맞는 한글 폰트 경로로 수정해주세요.
font_name = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font_name)

C:\Users\lotte\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

지역별 관광명소 데이터, 지역별 sns 언급량, 지역별 관광지명 검색 순위, 지역별 외내국인 방문자 수

In [79]:
area = pd.read_csv('area.csv')
sns_mentioned=pd.read_csv('sns_mentioned.csv')
ranking=pd.read_csv('ranking.csv')

In [80]:
area.drop(columns='index', inplace=True)

In [81]:
area

                   POI명        분류명      시도명  시군구명 법정동명
0                 간절곶등대      일반관광지    울산광역시   울주군  서생면
1                 고인돌공원      천연기념물     전라남도   순천시  송광면
2                  삼청동길      일반관광지    서울특별시   종로구  삼청동
3               선진전위치료기      일반관광지    광주광역시    북구  문흥동
4      설악산국립공원설악동탐방지원센터  관광안내소/매표소  강원특별자치도   속초시  설악동
...                 ...        ...      ...   ...  ...
25098           삼척맹방해변길      일반관광지  강원특별자치도   삼척시  근덕면
25099            영덕블루로드      일반관광지     경상북도   영덕군  강구면
25100            관악별빛산책       지역축제    서울특별시   관악구  신림동
25101             서면빛축제       지역축제    부산광역시  부산진구  부전동
25102              달빛야경     야영/캠핑장      경기도   화성시  송산동

[25103 rows x 5 columns]

In [82]:
area['지역명'] = area['시도명'] + ' ' + area['시군구명']

In [83]:
area = area.groupby('지역명').size().reset_index(name='관광지 수')

In [84]:
area

              지역명  관광지 수
0     강원특별자치도 강릉시    369
1     강원특별자치도 고성군    142
2     강원특별자치도 동해시     91
3     강원특별자치도 삼척시    179
4     강원특별자치도 속초시    109
..            ...    ...
244  충청북도 청주시 상당구    117
245  충청북도 청주시 서원구     19
246  충청북도 청주시 청원구     38
247  충청북도 청주시 흥덕구     30
248      충청북도 충주시    184

[249 rows x 2 columns]

In [85]:
sns_mentioned

     Unnamed: 0        검색량(건)           지역명
0             0  79394.833333   강원특별자치도 강릉시
1             1  23721.166667   강원특별자치도 고성군
2             2   5892.416667   강원특별자치도 동해시
3             3  18495.833333   강원특별자치도 삼척시
4             4  58979.500000   강원특별자치도 속초시
..          ...           ...           ...
167         167  23519.500000  충청북도 청주시 상당구
168         168  14599.083333  충청북도 청주시 서원구
169         169  15661.083333  충청북도 청주시 청원구
170         170  20685.000000  충청북도 청주시 흥덕구
171         171  21436.416667      충청북도 충주시

[172 rows x 3 columns]

In [86]:
sns_mentioned.drop(columns='Unnamed: 0', inplace=True)

In [87]:
sns_mentioned

           검색량(건)           지역명
0    79394.833333   강원특별자치도 강릉시
1    23721.166667   강원특별자치도 고성군
2     5892.416667   강원특별자치도 동해시
3    18495.833333   강원특별자치도 삼척시
4    58979.500000   강원특별자치도 속초시
..            ...           ...
167  23519.500000  충청북도 청주시 상당구
168  14599.083333  충청북도 청주시 서원구
169  15661.083333  충청북도 청주시 청원구
170  20685.000000  충청북도 청주시 흥덕구
171  21436.416667      충청북도 충주시

[172 rows x 2 columns]

In [88]:
ranking

,순위,광역시/도,시/군/구,관광지명,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
0,1,강원특별자치도,속초시,속초관광수산시장,강원 속초시 중앙로147번길 16-0,쇼핑,시장,805541
1,2,제주특별자치도,제주시,제주국제공항,제주 제주시 공항로 2-0,기타관광,교통시설,656221
2,3,충청북도,청주시 흥덕구,오송역,충북 청주시 흥덕구 오송가락로 123-0,기타관광,교통시설,644612
3,4,대전광역시,동구,대전역,대전 동구 중앙로 215-0,기타관광,교통시설,629223
4,5,부산광역시,해운대구,신세계백화점센텀시티점,부산 해운대구 센텀남대로 35-0,쇼핑,백화점,605647
...,...,...,...,...,...,...,...,...
211,212,울산광역시,동구,대왕암공원,울산 동구 등대로 95-0,문화관광,기타관광,74082
212,213,전라남도,구례군,화엄사,전남 구례군 화엄사로 539-0,역사관광,종교성지,73809
213,214,경상남도,창원시 의창구,창원종합버스터미널,경남 창원시 의창구 창원대로 371-0,기타관광,교통시설,73687
214,215,전북특별자치도,남원시,광한루원,전북 남원시 요천로 1447-0,기타관광,기타관광,73677
215,216,부산광역시,부산진구,부산시민공원,부산 부산진구 시민공원로 73-0,문화관광,기타관광,73120

In [89]:
ranking['지역명'] = ranking['광역시/도'] + ' ' + ranking['시/군/구']

In [90]:
# '지역명'을 기준으로 그룹화하여 '순위'의 평균 계산
ranking = ranking.groupby('지역명')['순위'].mean().reset_index()

ranking['평균 검색 순위'] = ranking['순위'].round().astype(int)
ranking.drop(columns='순위',inplace=True)

In [91]:
ranking

             지역명  평균 검색 순위
0    강원특별자치도 강릉시        91
1    강원특별자치도 고성군       184
2    강원특별자치도 속초시        94
3    강원특별자치도 양양군       146
4    강원특별자치도 원주시       158
..           ...       ...
84      충청북도 제천시       170
85  충청북도 청주시 상당구       115
86  충청북도 청주시 청원구        84
87  충청북도 청주시 흥덕구        80
88      충청북도 충주시       144

[89 rows x 2 columns]

In [92]:
visit=pd.read_csv('summed_visitors.csv')

In [93]:
visit

              지자체       방문자수
0     강원특별자치도 강릉시  100420235
1     강원특별자치도 고성군   21565109
2     강원특별자치도 동해시   36371996
3     강원특별자치도 삼척시   28384703
4     강원특별자치도 속초시   50236736
..            ...        ...
168  충청북도 청주시 상당구   66405031
169  충청북도 청주시 서원구   61531896
170  충청북도 청주시 청원구   59982550
171  충청북도 청주시 흥덕구   84803737
172      충청북도 충주시   83985509

[173 rows x 2 columns]

In [94]:
visit['지역명'] = visit['지자체']

In [95]:
visit.drop(columns='지자체',inplace=True)

In [96]:
visit

          방문자수           지역명
0    100420235   강원특별자치도 강릉시
1     21565109   강원특별자치도 고성군
2     36371996   강원특별자치도 동해시
3     28384703   강원특별자치도 삼척시
4     50236736   강원특별자치도 속초시
..         ...           ...
168   66405031  충청북도 청주시 상당구
169   61531896  충청북도 청주시 서원구
170   59982550  충청북도 청주시 청원구
171   84803737  충청북도 청주시 흥덕구
172   83985509      충청북도 충주시

[173 rows x 2 columns]

In [97]:
merged_df = area.merge(visit, on='지역명')\
                .merge(sns_mentioned, on='지역명')\
                .merge(ranking, on='지역명')

In [98]:
merged_df

             지역명  관광지 수       방문자수        검색량(건)  평균 검색 순위
0    강원특별자치도 강릉시    369  100420235  79394.833333        91
1    강원특별자치도 고성군    142   21565109  23721.166667       184
2    강원특별자치도 속초시    109   50236736  58979.500000        94
3    강원특별자치도 양양군    210   26277913  31640.166667       146
4    강원특별자치도 원주시    186  122883497  40661.500000       158
..           ...    ...        ...           ...       ...
76      충청북도 제천시    225   39844107  18040.666667       170
77  충청북도 청주시 상당구    117   66405031  23519.500000       115
78  충청북도 청주시 청원구     38   59982550  15661.083333        84
79  충청북도 청주시 흥덕구     30   84803737  20685.000000        80
80      충청북도 충주시    184   83985509  21436.416667       144

[81 rows x 5 columns]

In [99]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [100]:
X = merged_df[['관광지 수', '방문자수', '검색량(건)', '평균 검색 순위']]
# 방문자 수에 가중치 부여 (예: 2배)
X['방문자수'] = X['방문자수'] * 2
# 데이터 표준화
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# K-평균 클러스터링 (k=2)
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X_scaled)

C:\Users\lotte\AppData\Local\Temp\ipykernel_15968\3140875184.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['방문자수'] = X['방문자수'] * 2
C:\Users\lotte\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=2, random_state=42)

In [101]:
# 클러스터 라벨을 데이터프레임에 추가
merged_df['클러스터'] = kmeans.labels_

# 각 클러스터의 중심값 계산
cluster_centers = kmeans.cluster_centers_

In [102]:
# 각 클러스터의 특성 분석
cluster_summary = pd.DataFrame(cluster_centers, columns=['관광지 수', '방문자수', '검색량(건)', '평균 순위'])

In [103]:
cluster_summary

      관광지 수      방문자수    검색량(건)     평균 순위
0  0.108249  0.866964  0.584395 -0.722923
1 -0.070693 -0.566180 -0.381645  0.472113

In [104]:
# 주류 지역과 비주류 지역 라벨링 (기준: 방문자수)
# 평균 순위가 높을수록 낮은 값이 유리하기 때문에 이 경우 역순으로 정렬
if cluster_summary.loc[0].mean() > cluster_summary.loc[1].mean():
    merged_df['지역유형'] = merged_df['클러스터'].map({0: '주류 지역', 1: '비주류 지역'})
else:
    merged_df['지역유형'] = merged_df['클러스터'].map({0: '비주류 지역', 1: '주류 지역'})

In [105]:
merged_df[['지역명', '지역유형']]

             지역명    지역유형
0    강원특별자치도 강릉시   주류 지역
1    강원특별자치도 고성군  비주류 지역
2    강원특별자치도 속초시  비주류 지역
3    강원특별자치도 양양군  비주류 지역
4    강원특별자치도 원주시   주류 지역
..           ...     ...
76      충청북도 제천시  비주류 지역
77  충청북도 청주시 상당구  비주류 지역
78  충청북도 청주시 청원구  비주류 지역
79  충청북도 청주시 흥덕구   주류 지역
80      충청북도 충주시  비주류 지역

[81 rows x 2 columns]

In [106]:
major = merged_df[merged_df['지역유형'] == '주류 지역']['지역명'].tolist()
minor = merged_df[merged_df['지역유형'] == '비주류 지역']['지역명'].tolist()

In [107]:
print(major)

['강원특별자치도 강릉시', '강원특별자치도 원주시', '강원특별자치도 춘천시', '경상남도 거제시', '경상남도 양산시', '경상남도 창원시 성산구', '경상북도 경주시', '경상북도 구미시', '경상북도 포항시 북구', '광주광역시 광산구', '광주광역시 서구', '대구광역시 달서구', '대구광역시 동구', '대구광역시 북구', '대구광역시 중구', '대전광역시 동구', '대전광역시 서구', '대전광역시 유성구', '부산광역시 강서구', '부산광역시 금정구', '부산광역시 기장군', '부산광역시 부산진구', '부산광역시 사상구', '부산광역시 수영구', '부산광역시 해운대구', '울산광역시 울주군', '전라남도 순천시', '제주특별자치도 서귀포시', '제주특별자치도 제주시', '충청남도 아산시', '충청남도 천안시 동남구', '충청북도 청주시 흥덕구']

In [108]:
print(minor)

['강원특별자치도 고성군', '강원특별자치도 속초시', '강원특별자치도 양양군', '강원특별자치도 정선군', '강원특별자치도 평창군', '강원특별자치도 홍천군', '경상남도 남해군', '경상남도 진주시', '경상남도 창원시 마산회원구', '경상남도 창원시 의창구', '경상남도 통영시', '경상남도 하동군', '경상북도 김천시', '경상북도 안동시', '경상북도 영덕군', '경상북도 포항시 남구', '광주광역시 동구', '대구광역시 달성군', '대구광역시 서구', '대전광역시 대덕구', '대전광역시 중구', '부산광역시 동구', '부산광역시 동래구', '부산광역시 북구', '부산광역시 사하구', '부산광역시 영도구', '부산광역시 중구', '울산광역시 남구', '울산광역시 동구', '울산광역시 중구', '전라남도 광양시', '전라남도 구례군', '전라남도 담양군', '전라남도 목포시', '전라남도 여수시', '전라남도 완도군', '충청남도 공주시', '충청남도 당진시', '충청남도 보령시', '충청남도 서산시', '충청남도 서천군', '충청남도 예산군', '충청남도 천안시 서북구', '충청남도 태안군', '충청북도 단양군', '충청북도 제천시', '충청북도 청주시 상당구', '충청북도 청주시 청원구', '충청북도 충주시']